title: The Lost
description: HMS's website
theme: just-the-docs

url: https://hmsyuan.github.io

aux_links:
  Template Repository: https://github.com/hmsyuan/hmsyuan.github.io

# website's logo and favicon
# logo: ""
# favicon_ico: ""

# footer content
# markup / liquid-based content.
footer_content: "All contents' copyright on this site are reserved by HMS 2023"

# color:light(default) and dark 
color_scheme: light

# page and post default
# layout setting about jekyll can refer:https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scopes:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  -
    scopes:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "HMS"
